### ISSUE TITLE
Need the ability to manipulate the response from Om Server API

### ISSUE THREAD

**Issue by awkay** [untangled-web/untangled-server#17]
Om mutations like `login` should be able to affect responses. For example, we should be able to add cookies, other headers, change the status code, etc.

I'm suggesting that top-level queries and mutations be able to return a response like this:

```
(defn some-mutation [env k p]
   (response-with-status { :tempids {n m} } 202))
```

and have that (probably through metadata) affect the underlying response to the client.

**Comment by wilkerlucio** [comment]
I just found myself needing it as well to change the `:session`.

**Comment by Pancia** [comment]
Merged in https://github.com/untangled-web/untangled-server/pull/20
