### ISSUE TITLE
Fingerprint Assets

### ISSUE THREAD

**Issue by currentoor** [untangled-web/untangled-server#2]
Untangled already gzips and etags response but it doesn't look like there is any fingerprinting for static assets. I was thinking we could do something like this:

https://github.com/DanThiffault/boot-pages

Thoughts?

**Comment by awkay** [comment]
That would be easy enough to integrate as a component that can inject itself into the Ring stack. Not sure I'd want it in there by default. Are you trying to address too-aggressive caching? E.g. the timestamp has changed but the browser uses the cached version anyway?

**Comment by currentoor** [comment]
That makes sense. I'm not trying to address too-aggressive caching. Just wanted fingerprinted assets in production for page load time. I don't mind making a custom component in my app.
