### ISSUE TITLE
Allow Configuration of http-kit

### ISSUE THREAD

**Issue by adstage-david** [untangled-web/untangled-server#4]
We're running into a problem with http kit complaining about us having too large headers - turns out this is due to cookies. The error is: https://github.com/http-kit/http-kit/issues/196

To work around this, we probably need to expand the amount of space for the cookies header to match more what other http servers do (as mentioned in the above issue) - this configuration option currently is not exposed by Untangled. From slack discussion, best option is to allow changing other http-kit config options from the configuration file.

**Comment by currentoor** [comment]
https://github.com/untangled-web/untangled-server/pull/5
